# Generated by Django 6.0.4 on 2026-05-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_name', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('height', models.IntegerField()),
                ('wood_choice', models.CharField(max_length=50)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.IntegerField()),
                ('wood_type', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
